---
certbot__email: 'kotovalexarian@gmail.com'
certbot__cert_name: 'gamma.libertarian-party.com'
certbot__cert_domains:
  - 'gamma.libertarian-party.com'

nginx__remove_default: true

nginx__sites:
  - type: xxxxx
    domain: 'gamma.libertarian-party.com'
    cert:     '/etc/letsencrypt/live/gamma.libertarian-party.com/fullchain.pem'
    key:      '/etc/letsencrypt/live/gamma.libertarian-party.com/privkey.pem'
    ssl_conf: '/etc/letsencrypt/options-ssl-nginx.conf'
