---
- name: Add Yarn APT key
  apt_key:
    id: 72ECF46A56B4AD39C907BBB71646B01B86E50310
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn APT repository
  copy:
    src: files/yarn.list
    dest: /etc/apt/sources.list.d/yarn.list
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
