---
- name: Install Vim
  apt:
    update_cache: true
    name: vim

- name: Set Vim as default editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: Install Vim config
  copy:
    src: files/vimrc.local
    dest: /etc/vim/vimrc.local
    mode: 'u=rw,g=r,o=r'
    owner: root
    group: root
