---
- hosts: postgres.libertarian-party.com
  module_defaults:
    apt:
      force_apt_get: true
  roles:
    - role: ../roles/common
      tags: common
    - role: ../roles/postgresql
      tags: postgresql
  tasks:
    - name: Create PostgreSQL database
      become: true
      become_user: postgres
      postgresql_db:
        name: partynest_production

    - name: Create PostgreSQL deploy user
      become: true
      become_user: postgres
      postgresql_user:
        db: partynest_production
        name: partynest
        password: password

    - name: Create PostgreSQL staff user
      become: true
      become_user: postgres
      postgresql_user:
        db: partynest_production
        name: partynest_staff
        password: staff_password

    - name: Create PostgreSQL public user
      become: true
      become_user: postgres
      postgresql_user:
        db: partynest_production
        name: partynest_public
        password: public_password
